#!/usr/bin/env python3
import sys
from configparser import ConfigParser 
cfg=ConfigParser()
cfg.read_file(sys.stdin)
sys.stdout.write(cfg['options']['install_requires'])
sys.stdout.write(cfg['options.extras_require']['test'])
