version: "3.3" 

services:
  nfatools-dev:
    image: nfatools:latest
    env_file: .env
    environment:
      NFATOOLS_COMMAND: shell
      NFATOOLS_PROFILE: nfatools/form3/test
    networks:
      - selenium 
    volumes:
      - type: bind
        source: ${PWD}/nfatools/home
        target: /home/nfatools

networks:
  selenium:
