version: "3.3" 

services:
  nfatools:
    image: nfatools
    build:
      context: nfatools 
      args:
        USER: nfatools
        UID: 1000
        GID: 1000
    restart: unless-stopped
    env_file: .env
    networks:
      - selenium 

  selenium:
    image: selenium/standalone-chrome-debug:latest
    restart: unless-stopped
    ports:
      - 4444:4444
      - ${VNC_PORT:-5900}:5900
    env_file: .env
    environment:
      GRID_DEBUG: "true"
      SE_OPTS: "-debug"
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1080

    volumes:
      - /dev/shm:/dev/shm
      - type: bind
        source: ${PWD}/download
        target: /var/download
    networks:
      - selenium 

networks:
  selenium:
